// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { HorizontalBox, VerticalBox, StandardTableView, GroupBox, StyleMetrics, LineEdit } from "std-widgets.slint";
import { GallerySettings } from "../gallery_settings.slint";
import { Page } from "page.slint";

export component WizardStartPage inherits Page {
    title: @tr("Wizard Start Page");
    Text {
        text: @tr("Welcome to the NPBackup wizard.\n\nUse the side bar to navigate through the different steps of the wizard.");
    }

    // Spacer
    Rectangle { }
}