{
 "title": "NPBackup Statistics",
 "description": "Show status of restic backups done with NPBackup",
 "tags": [
  "backups",
  "restic"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "backup_job", "query": { "query": "label_values(backup_job)" } },
   { "name": "tenant", "query": { "query": "label_values(tenant)" } }
  ]
 },
 "panels": [
  {
   "title": "NPBackup Success & Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "description": "Number of succesful npbackup executions",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time((restic_backup_failure{backup_job=~'$backup_job'} == 0)[$__range:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success",
   "type": "table",
   "description": "List of latest npbackup execution success",
   "gridPos": { "h": 9, "w": 22, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time((restic_backup_failure{backup_job=~'$backup_job'} == 0)[$__range:])",
     "legendFormat": "{{ backup_job }}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Number of failed npbackup executions",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time((restic_backup_failure{backup_job=~'$backup_job'} == 1)[$__range:]))"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "table",
   "description": "List of latest npbackup execution failures",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 10 },
   "targets": [
    {
     "expr": "count_over_time((restic_backup_failure{backup_job=~'$backup_job'} == 1)[$__range:])",
     "legendFormat": "{{ backup_job }}"
    }
   ]
  },
  {
   "title": "Backup operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "config",
   "targets": [
    {}
   ]
  },
  {
   "title": "Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "restic_backup_duration_seconds{backup_job=~\"$backup_job\"}",
     "legendFormat": "{{backup_job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "restic_repo_size_bytes{backup_job=~\"$backup_job\"}",
     "legendFormat": "total size in restore mode - {{ backup_job }}"
    }
   ]
  },
  {
   "title": "Added bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "restic_repo_size_files_stored_bytes{backup_job=~\"$backup_job\"}",
     "legendFormat": "total added bytes - {{ backup_job }}"
    }
   ]
  },
  {
   "title": "Number of files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(restic_repo_files{backup_job=~\"$backup_job\",state=\"changed\"}) by (backup_job)",
     "legendFormat": "changed - {{ backup_job }}"
    },
    {
     "expr": "sum(restic_repo_files{backup_job=~\"$backup_job\",state=\"new\"}) by (backup_job)",
     "legendFormat": "new - {{ backup_job }}"
    },
    {
     "expr": "sum(restic_repo_files{backup_job=~\"$backup_job\",state=\"unmodified\"}) by (backup_job)",
     "legendFormat": "unmodified - {{ backup_job }}"
    },
    {
     "expr": "sum(restic_repo_files{backup_job=~\"$backup_job\",state=\"total\"}) by (backup_job)",
     "legendFormat": "processed - {{ backup_job }}"
    }
   ]
  },
  {
   "title": "Number of directories",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(restic_repo_dirs{backup_job=~\"$backup_job\",state=\"changed\"}) by (backup_job)",
     "legendFormat": "changed - {{ backup_job }}"
    },
    {
     "expr": "sum(restic_repo_dirs{backup_job=~\"$backup_job\",state=\"new\"}) by (backup_job)",
     "legendFormat": "new - {{ backup_job }}"
    },
    {
     "expr": "sum(restic_repo_dirs{backup_job=~\"$backup_job\",state=\"unmodified\"}) by (backup_job)",
     "legendFormat": "unmodified - {{ backup_job }}"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "restic_backup_duration_seconds{backup_job=~'$backup_job'}",
     "legendFormat": "{{ backup_job }}"
    }
   ]
  },
  {
   "title": "Processed size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "restic_repo_size_files_stored_bytes{backup_job=~'$backup_job'}",
     "legendFormat": "{{ backup_job }}"
    }
   ]
  }
 ]
}