#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# This file is part of npbackup, and is really just a shortcut to npbackup.py for linux

from npbackup import *

if __name__ == "__main__":
    main()
